### ISSUE TITLE
Space issue between 2 words

### ISSUE THREAD

**Issue by satishsharma-riseandinspire** [dothinking/pdf2docx#103]
Hi,

I am using pdf2docx version v0.5.1. At the time of pdf to Docx conversion somewhere in converted Docx file space is missing between 2 words.
Kindly help.

Thanks

**Comment by dothinking** [comment]
Many thanks for reporting this. 

It would be great if you can provide the pdf file, only the issue page should be enough.

**Comment by satishsharma-riseandinspire** [comment]
[Space-error-349377.docx](https://github.com/dothinking/pdf2docx/files/6738036/Space-error-349377.docx)
[Space-error-360548.pdf](https://github.com/dothinking/pdf2docx/files/6738038/Space-error-360548.pdf)

PFA, both pdf file and converted Docx file.

Thanks

**Comment by dothinking** [comment]
thanks for providing the test files. The root cause is that the source pdf does miss the space, while it won't affect the reading since the missing space is just at the end of a line.  But words position is changed after docx conversion, so the missing space is observed explicitly. 

it's a very good point, reminding to improve `pdf2docx` at least on two aspects: 

- either ensure same line break with pdf;
- or add a space for those words at the end of a line if they don't have one.

**Comment by dothinking** [comment]
This issue was fixed per the `dev` branch. Is it possible for you to upgrade to this developing version？

```
$ pip install git+git://github.com/dothinking/pdf2docx.git@dev --upgrade
```

**Comment by dothinking** [comment]
Closed for now.

**Comment by dothinking** [comment]
Closed for now.
