### ISSUE TITLE
local variable 'x0' referenced before assignment

### ISSUE THREAD

**Issue by rizwanAtAppening** [dothinking/pdf2docx#104]
while converting from pdf to docx.
it gives this error

[INFO] Start to convert test2.pdf
[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
[ERROR] local variable 'x0' referenced before assignment

Platform Ubuntu 18

![image](https://user-images.githubusercontent.com/62502221/126144783-884ae39d-b72a-4435-9d52-c58aa84a9e7f.png)

**Comment by dothinking** [comment]
It seems an issue from the upstream library `PyMuPDF`, it's great if you could provide more info below

- the version of `PyMuPDF`, e.g.
  ```
  pip list | grep PyMuPDF
  ```

- the pdf file you used
  In case your pdf has confidential info, is it possible to delete all text but keep the figures only? Because this issue seems caused by vector graphics.

**Comment by rizwanAtAppening** [comment]
Sorry for late reply, seem to work when upgrade to pytho3.9.
but here is the file and version you needed, its not working with python3.6.9
[TEST_CASE.pdf](https://github.com/dothinking/pdf2docx/files/6906023/TEST_CASE.pdf)
![image](https://user-images.githubusercontent.com/62502221/127623202-44c0b535-88d1-45b3-a7a0-bd08571b91a3.png)

**Comment by BinhLTTB** [comment]
It might be cause by PyMuPDF version. I got this error when upgrade PyMuPDF from version 1.18.13 to 1.18.15

**Comment by dothinking** [comment]
@rizwanAtAppening @BinhLTTB many thanks for your reply.

I did the following tests:

- PyMuPDF 1.18.13 + python 3.6 (or 3.9) -> no issue
- PyMuPDF 1.18.15 + python 3.6 (or 3.9) -> same issue
- PyMuPDF 1.18.15 + python 3.6 (or 3.9) + minor change the pdf (e.g. any words) and re-save -> no issue

Comparing test 1 with test 2, obviously, it's an issue caused by PyMuPDF 1.18.15.

Test 3 is interesting, saving the pdf with a minor change, the issue was fixed. I guess there was a "bad" element in the original pdf, while it's fixed automatically by the pdf editor when I changed anything and re-save it. So, it works for PyMuPDF 1.18.15 again. Without further investigation, I guess it's the re-saving rather than python3.9 fixed your issue, @rizwanAtAppening.
