### ISSUE TITLE
raise ValueError("no valid image found")

### ISSUE THREAD

**Issue by jonnyhoff** [dothinking/pdf2docx#66]
Processing PDF with svg images

**Comment by dothinking** [comment]
Could you please upload your failed page for test? Thank you.

**Comment by jonnyhoff** [comment]
Unfortunately I can't due to the information being confidential.

**Comment by dothinking** [comment]
Understood. Then could you please test it with the latest version v0.5.0 at your convenience, and provide the detailed error log? Thank you in advance. 

The upstream library `PyMuPDF` can extract only raster images like png and jpeg, while can't understand vector graphics since they're composed of just lines and curves according to pdf specifications. So, definitely this project can't process svg images precisely, but try to crop the page area where svg may exist. As I understand, it shouldn't raise such no valid image error. Anyway, I'll look into it further next days.
