### ISSUE TITLE
AssertionError: corrupt cmap table format 4 (data length: 34, header length: 40)

### ISSUE THREAD

**Issue by BinhLTTB** [dothinking/pdf2docx#95]
I have some trouble when converting this file, I tried to convert each page separately but still got the same error. 
It still works fine with other files. 
Here is the sample: 
[sample_test.pdf](https://github.com/dothinking/pdf2docx/files/6584368/sample_test.pdf)

**Comment by dothinking** [comment]
Thanks again, BinhLTTB. It's an issue when checking the embedded font. The latest `dev` branch should fix it.

```
$ pip install git+git://github.com/dothinking/pdf2docx.git@dev --upgrade
```

But, it seems the bullet symbol is broken in the converted docx. For now, you need to fix it manually by changing the font of bullet symbol from `Symbol` to any other font like `Arial`. 

I should work on the list style next since it has been in my backlog for so long time.

**Comment by dothinking** [comment]
Closed for now. Feel free to reopen it if any further comments.
