### ISSUE TITLE
[WARNING] Ignore page due to error

### ISSUE THREAD

**Issue by ishineko** [dothinking/pdf2docx#97]
Quick question:

When a page is ignored during conversion, the only feedback is through the messages on the console telling us that the page was skipped, but if the system is running unattended the user doesn't know that anything failed.

Is it possible for the calling function to capture that there's a problem, and decide how to handle it?

Thanks!

**Comment by dothinking** [comment]
Many thanks for your suggestion. 

The initial thought is not to break the conversion process due to failure of a certain page, while your case also makes sense. So, how about adding an argument, say `ignore_page_error`, so that the user could decide what to do: keep going if True, otherwise just raise the Exception?

The related code is around Line 190 in file `converter.py`:

```python
# create page by page        
docx_file = Document() 
num_pages = len(parsed_pages)
for i, page in enumerate(parsed_pages, start=1):
    if not page.finalized: continue # ignore unparsed pages
    logging.info('(%d/%d) Page %d', i, num_pages, page.id+1)
    try:
        page.make_docx(docx_file)
    except Exception as e:
        logging.error('Ignore page due to error: %s', e)

# save docx
docx_file.save(filename)
```

For now, you can just remove the try-except wrapper, then catch it in the calling function.

**Comment by dothinking** [comment]
Adding argument `ignore_page_error`, it might look like:

```python
# create page by page        
docx_file = Document() 
num_pages = len(parsed_pages)
for i, page in enumerate(parsed_pages, start=1):
    if not page.finalized: continue # ignore unparsed pages
    logging.info('(%d/%d) Page %d', i, num_pages, page.id+1)
    try:
        page.make_docx(docx_file)
    except Exception as e:
        if ignore_page_error:
            logging.error('Ignore page due to error: %s', e)
        else:
            raise MakedocxException(f'Error in page {page.id}: {e}')

# save docx
docx_file.save(filename)
```

where `MakedocxException` is used to filter the Exception type.

```python
class ConversionException(Exception): 
    pass

class MakedocxException(ConversionException): 
    pass
```

**Comment by ishineko** [comment]
Awesome! This is exactly what I needed, and it works great! Thanks for all your help! :-)
